### ISSUE TITLE
why don't we support code snippet generation on subscription

### ISSUE THREAD

**Issue by wangshijun** [OneGraph/graphiql-code-exporter#23]
I looked into the source code and found this: https://github.com/OneGraph/graphiql-code-exporter/blob/master/src/CodeExporter.js#L75

**Comment by sgrove** [comment]
This is a great question - we'll be releasing one soon with support! The challenge is really around how specific each GraphQL service is, so it's hard for generic snippets to support. But we'll make it so that specific, custom, provider-aware snippets can include it!

**Comment by sgrove** [comment]
@wangshijun looking into this with #35
